### ISSUE TITLE
Terminal Command bug?

### ISSUE THREAD

**Issue by LotusYaj** [clementinise/CustomSounds#5] opened 2023-12-30 09:06 UTC
I never had these issues before up until I believe the release of 2.2.0, but the term command "CS RL" just reverts back to the game's original sounds and doesn't show the prompt for "Customsounds reloaded!" (or whatever it was). Before it would work as intended.

"CS L" would also work at first but after the "CS RL", it shows nothing.

(keeping it short with using the shorter command but both short and long commands do not work)
>With my current mod profile on R2MM (with 50+ mods) , disabled all the terminal plus/api mods thinking it would fix it. It didn't.

>Created a new profile with the minimal mods to play with others plus CS. Tried the term command again and the same problem persists.

>Have not tested if LCSoundTool is the cause.

-Attached notepad file of console error when it occured.
[CSoundsErrorMsg.txt](https://github.com/clementinise/CustomSounds/files/13797577/CSoundsErrorMsg.txt)

**Comment by LotusYaj** [comment] 2023-12-30 09:13
Edit:

**Comment by feralcode** [comment] 2023-12-30 23:50
I have been having this exact issue since 2.1.2. 

![image](https://github.com/clementinise/CustomSounds/assets/78993459/97976ca2-fa6c-4900-97c6-2b337e796518)

**Comment by Danice123** [comment] 2024-01-01 03:40
Above error is caused by an issue in 1.4.0 of LCSoundTool, reverting to 1.3.2 will fix this issue. Next release of LCSoundTool will also fix this issue

See issue https://github.com/clementinise/CustomSounds/issues/3

**Comment by clementinise** [comment] 2024-01-18 12:18
This is fixed in 2.3.0. Update release on Thunderstore, Github will soon be updated too!

**Closed as completed by clementinise** 2024-01-18 12:18 UTC
